plugins {
    id 'java'
}

group = 'org.test'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
    implementation 'io.qameta.allure:allure-junit5:2.19.0'
    implementation 'org.assertj:assertj-core:3.27.3'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.16.1'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-chrome-driver', version: '4.16.1'
}

test {
    useJUnitPlatform()
}